/**
 * Corpus grounding: a project may ship a compact index of the corpus it answers
 * from (authored, or generated by the project's own tooling). It is appended to
 * the prompt — never the full corpus text — so the advisor knows what exists
 * and how to cite it without blowing the token budget. haivn_eip indexes legal
 * instruments; ppol5013 and papers index readings.
 */
import fs from 'fs/promises';
import path from 'path';
import type { ChatProjectConfig } from './types.js';

/** Candidate files under projects/<slug>/, in order; the first that reads wins. */
const LEGACY_CANDIDATES = [
  ['content', 'legal', 'grounding.md'],
  ['content', 'readings', 'grounding.md'],
];

/** The grounding text, or '' when the project has none. */
export async function loadCorpusGrounding(repoRoot: string, cfg: ChatProjectConfig): Promise<string> {
  for (const rel of LEGACY_CANDIDATES) {
    try {
      return await fs.readFile(path.join(repoRoot, 'projects', cfg.slug, ...rel), 'utf-8');
    } catch { /* try the next candidate */ }
  }
  return '';
}
